#!/usr/bin/env python3
"""Adopter-provided path lint and inventory for the Spec-Agentic-SDLC corpus (issue #14).

The corpus documents controls that are *implemented* in the product repository that adopts it,
so many files name paths and commands that do not exist here (src/, make targets, services.yaml,
scripts/governance/, .github/workflows/). Every such file must say so, with either the corpus
banner ("Documentation-corpus edition") or the marker  <!-- adopter-paths -->  (Markdown) /
# adopter-paths  (YAML). This script:

  --check      exit 1 and list files that reference adopter paths without a marker (CI mode)
  --inventory  print the Markdown inventory (path → who provides it → files citing it)
  --mark       insert the marker into every unmarked file (idempotent; after frontmatter)
"""
import re, sys, os, glob, collections

MARKER_MD = "<!-- adopter-paths: names paths or commands provided by the adopting product repository — see docs/reference/adopter-provided-paths.md -->"
MARKER_YAML = "# adopter-paths: names paths or commands provided by the adopting product repository — see docs/reference/adopter-provided-paths.md"
BANNER = "Documentation-corpus edition"
SKIP = ("docs/reference/repository-template-v2-README.md", "docs/reference/repository-template-v2-SETUP.md",
        "docs/reference/adopter-provided-paths.md")
MAKE_TARGETS = r"(help|setup(?:-[a-z]+)?|infra-[a-z]+|run(?:-[a-z]+)?|test(?:-[a-z-]+)?|lint(?:-[a-z]+)?|format(?:-[a-z]+)?|docs-serve|openapi-ui|asyncapi-ui|gen-[a-z-]+|deploy-[a-z]+|rollback|new-service|sbom|doctor|sync-develop|check-[a-z-]+|verify-[a-z0-9-]+|burn-in-status|smoke|template-init|check-versions|migrate(?:-[a-z]+)?|build(?:-[a-z]+)?)"
PATTERNS = collections.OrderedDict([
    ("src/",                 (re.compile(r"(?<![A-Za-z0-9_./-])src/"),                 "application code")),
    ("make <target>",        (re.compile(r"\bmake " + MAKE_TARGETS + r"\b"),             "Makefile targets / CI equivalents")),
    ("services.yaml",        (re.compile(r"\bservices\.yaml\b"),                        "service and topic registry")),
    ("scripts/governance/",  (re.compile(r"scripts/governance/"),                       "deterministic governance gates (Python)")),
    (".github/workflows/",   (re.compile(r"\.github/workflows/"),                       "CI/CD pipelines")),
])

def files():
    out = []
    for pat in ("**/*.md", "**/*.yaml", "**/*.yml"):
        for p in glob.glob(pat, recursive=True):
            if p.startswith((".git/", ".serena/", ".sdd/", "node_modules/")) or p in SKIP:
                continue
            out.append(p)
    return sorted(set(out))

def hits(text):
    return [k for k, (rx, _) in PATTERNS.items() if rx.search(text)]

def marked(p, text):
    return BANNER in text or MARKER_MD in text or MARKER_YAML in text or "<!-- adopter-paths" in text or "# adopter-paths" in text

def scan():
    res = {}
    for p in files():
        t = open(p, encoding="utf-8", errors="replace").read()
        h = hits(t)
        if h:
            res[p] = (h, marked(p, t))
    return res

def insert_marker(p):
    t = open(p, encoding="utf-8").read()
    if p.endswith((".yaml", ".yml")):
        lines = t.split("\n")
        i = 1 if lines and lines[0].startswith("#!") else 0
        lines.insert(i, MARKER_YAML)
        open(p, "w", encoding="utf-8").write("\n".join(lines))
        return
    if t.startswith("---\n"):
        end = t.find("\n---", 4)
        if end != -1:
            end = t.find("\n", end + 1)
            head, rest = t[:end + 1], t[end + 1:]
            open(p, "w", encoding="utf-8").write(head + "\n" + MARKER_MD + "\n" + rest.lstrip("\n"))
            return
    open(p, "w", encoding="utf-8").write(MARKER_MD + "\n\n" + t)

def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    res = scan()
    if mode == "--inventory":
        print("# Adopter-provided paths\n")
        print("<!-- adopter-paths: this inventory is generated by scripts/python/adopter_paths.py --inventory -->\n")
        print("This corpus is documentation. The paths and commands below are referenced throughout it but are")
        print("**provided by the product repository that adopts the corpus** (see `SETUP.md` §2). A file that")
        print("names one of them must carry the corpus banner or the `adopter-paths` marker; the")
        print("`check-corpus.sh` gate (C7) enforces it. Regenerate this page with")
        print("`python3 scripts/python/adopter_paths.py --inventory > docs/reference/adopter-provided-paths.md`.\n")
        print("| Referenced path / command | Provided by the adopting repository as | Files citing it |")
        print("| --- | --- | --- |")
        for k, (_, what) in PATTERNS.items():
            n = sum(1 for p, (h, _) in res.items() if k in h)
            print(f"| `{k}` | {what} | {n} |")
        print(f"\n**Files referencing at least one adopter path:** {len(res)} · marked: {sum(1 for h,m in res.values() if m)} · unmarked: {sum(1 for h,m in res.values() if not m)}\n")
        print("## By directory\n")
        by = collections.Counter(p.split('/')[0] if '/' in p else '(root)' for p in res)
        print("| Directory | Files |\n| --- | --- |")
        for d, n in sorted(by.items(), key=lambda kv: -kv[1]):
            print(f"| `{d}` | {n} |")
        return 0
    if mode == "--mark":
        n = 0
        for p, (h, m) in res.items():
            if not m:
                insert_marker(p); n += 1
        print(f"marked {n} file(s)")
        return 0
    bad = [p for p, (h, m) in res.items() if not m]
    print(f"{len(res)} file(s) reference adopter paths; {len(bad)} unmarked")
    for p in bad:
        print(f"  {p}: {', '.join(res[p][0])}")
    return 1 if bad else 0

if __name__ == "__main__":
    sys.exit(main())
